version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file: ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
    ports:
      - 27019:27017
    volumes:
      - ./data/db:/data/db:z
    env_file: ./.env
